### ISSUE TITLE
Question 14: Two identical options, one 'incorrect'

### ISSUE THREAD

**Issue by grey-lock** [learn-co-curriculum/quiz-css-fundamentals#4]
Selecting the 1st of two options: `a.hover { color: red; }` causes an incorrect response.

**Comment by gj** [comment]
Hi @TheInvalidNonce !

`a.hover` is not the same thing as `a:hover`.

If you have further questions, head on over to the [Ask a Question](http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson) (AAQ) feature, where the [Technical Coaches](http://help.learn.co/instructional-support/receiving-course-support/who-are-the-technical-coaches) (on [supported tracks](http://help.learn.co/instructional-support/receiving-course-support/does-my-program-or-course-have-technical-coach-support)) and fellow community members can help you figure it out. For some tips on how to take full advantage of AAQ, check out [this helpful article](http://help.learn.co/ask-a-question/how-to-optimize-time-in-ask-a-question) in the [Learn Help Center](http://help.learn.co/).

Thanks! 💙
